---
title: "| Survival Analysis    \n| Data Wrangling & Feature Engineering\n"
author: "April Leclair"
date: "2018-02-11"
output:
  bookdown::tufte_html2:
    number_sections: no
    split_by: none
    toc: no
  bookdown::pdf_document2:
    latex_engine: pdflatex
    number_sections: no
    toc: no
  bookdown::tufte_handout2:
    latex_engine: xelatex
    number_sections: no
    toc: no
  bookdown::html_document2:
    number_sections: no
    split_by: none
    toc: no
---
 
```{r setup, include=FALSE, message=FALSE}
library(tidyverse)
library(readr)
knitr::opts_chunk$set(tidy = FALSE, message=FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

# Load Data 
```{r message=FALSE, warning=FALSE}
houseTC_final <- read_csv("../Source/houseTC_final.csv")
```

# Variable Names
```{r}
names(houseTC_final)
```

# Feature Engineering

* `tom` = Time on Market
* `pdiff` = Price Difference
* `pdiff_perc` = Price Difference in Percentage 
* `pdiff_np` = Factored variable of `1` = positive `pdiff`, `2` = negative `pdiff`, `3` = 0 `pdiff`

```{r warning = FALSE, message=FALSE}
house_TC <- houseTC_final %>%
  mutate(tom = as.numeric(soldatdate - listedatdate),
         prdiff = soldatpr - listedatpr,
         prdiff_perc = (soldatpr - listedatpr)/listedatpr,
         prdiff_np = as.factor(ifelse(prdiff > 0, 1, 
                            ifelse(prdiff < 0, 2,
                                   ifelse(prdiff == 0, 3, 5)))),
         city = as.factor(city),
         pid = as.factor(pid),
         address = as.factor(address),
         neighb = as.factor(neighb))

save(house_TC, file = "../Source/house_TC.Rda")
write_csv(house_TC, "../Source/house_TC.csv")
```


## Inspect Variables

### `tom`
```{r}
# tem %>%
#   arrange(desc(tom))
# tem %>%
#   arrange(tom)
max(tem$tom)
min(tem$tom)
mean(tem$tom)
median(tem$tom)
```

### `tom` by city
```{r}
# Saint Paul
stp <- tem %>%
  filter(city == "Saint Paul") %>%
  arrange(desc(tom))
stp %>%
  filter(city == "Saint Paul") %>%
  arrange(tom)
max(stp$tom)
min(stp$tom)
mean(stp$tom)
median(stp$tom)

# Minneapolis
min <- tem %>%
  filter(city == "Minneapolis") %>%
  arrange(desc(tom))
min %>%
  filter(city == "Minneapolis") %>%
  arrange(tom)
max(min$tom)
min(min$tom)
mean(min$tom)
median(min$tom)

table(tem$city)
```


### `prdiff`
```{r}
tem %>%
  arrange(desc(prdiff))
tem %>%
  arrange(prdiff)
max(tem$prdiff)
min(tem$prdiff)
mean(tem$prdiff)
median(tem$prdiff)
```

```{r warning = FALSE, message=FALSE}
tem %>% ggplot(aes(prdiff, tom)) +
  geom_point(show.legend = TRUE)
```

### `prdiff` by city
```{r}
# Saint Paul
stp <- tem %>%
  filter(city == "Saint Paul") %>%
  arrange(desc(prdiff))
stp %>%
  filter(city == "Saint Paul") %>%
  arrange(prdiff)
max(stp$prdiff)
min(stp$prdiff)
mean(stp$prdiff)
median(stp$prdiff)

# Minneapolis
min <- tem %>%
  filter(city == "Minneapolis") %>%
  arrange(desc(prdiff))
min %>%
  filter(city == "Minneapolis") %>%
  arrange(prdiff)
max(min$prdiff)
min(min$prdiff)
mean(min$prdiff)
median(min$prdiff)

```

### `prdiff_np`
```{r}
table(tem$prdiff_np)
81/sum(81, 193,  37)
193/sum(81, 193,  37)
37/sum(81, 193,  37)
```

```{r warning = FALSE, message=FALSE}
tem %>% ggplot(aes(prdiff_np, tom)) + 
  geom_bar(stat = "identity", position = "stack", show.legend = TRUE) +
  labs(title = "Short, Long Sold at Price & Time on Market")
```


### `schdist`
```{r warning = FALSE, message=FALSE}
tem %>%
  arrange(desc(schdist))
tem %>%
  arrange(schdist)
max(tem$schdist)
min(tem$schdist)
mean(tem$schdist)
median(tem$schdist)

tem %>% ggplot(aes(schdist)) +
  geom_histogram(stat = "bin", bins = 30) +
  labs(title = "Histogram of School Distance")
```
